Question 6 -
Using the data from Question 3, write code to analyze the data and answer the following questions Note 1.
Draw plots to demonstrate the analysis for the following questions for better visualizations.
2. Write code comments wherever required for code understanding
Insights to be drawn -
● Get all Pokemons whose spawn rate is less than 5%
● Get all Pokemons that have less than 4 weaknesses
● Get all Pokemons that have no multipliers at all
● Get all Pokemons that do not have more than 2 evolutions
● Get all Pokemons whose spawn time is less than 300 seconds.
Note - spawn time format is "05:32”, so assume “minute: second” format and perform the analysis.
● Get all Pokemon who have more than two types of capabilities

In [1]:
import pandas as pd

df = pd.read_excel("C:/Users/jayku/Downloads/Pokeman_data.xlsx")
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              151 non-null    int64
 1   num             151 non-null    int64
 2   name            151 non-null    object
 3   img             151 non-null    object
 4   type            151 non-null    object
 5   height          151 non-null    object
 6   weight          151 non-null    object
 7   candy           151 non-null    object
 8   candy_count     70 non-null     float64
 9   egg             151 non-null    object
 10  spawn_chance    151 non-null    float64
 11  avg_spawns      151 non-null    float64
 12  spawn_time      145 non-null    object
 13  multipliers     70 non-null     object
 14  weaknesses      151 non-null    object
 15  next_evolution  70 non-null     object
 16  prev_evolution  72 non-null     object
dtypes: float64(3), int64(2), object(12)
memory usage: 20.2+ KB

**Checking for duplicates**

In [3]:
df.duplicated().count()

151

**no duplicates are present**

**Q1:Get all Pokemons whose spawn rate is less than 5%**

## pokemons whose spawn rate is less than 5%

In [4]:
pd.options.display.max_rows=200
df[df['spawn_chance']<0.05][['num','name','spawn_chance']]

     num        name  spawn_chance
1      2     Ivysaur        0.0420
2      3    Venusaur        0.0170
4      5  Charmeleon        0.0120
5      6   Charizard        0.0031
7      8   Wartortle        0.0340
8      9   Blastoise        0.0067
11    12  Butterfree        0.0220
25    26      Raichu        0.0076
27    28   Sandslash        0.0370
30    31   Nidoqueen        0.0120
33    34    Nidoking        0.0170
35    36    Clefable        0.0120
37    38   Ninetales        0.0077
39    40  Wigglytuff        0.0180
44    45   Vileplume        0.0097
50    51     Dugtrio        0.0140
52    53     Persian        0.0220
56    57    Primeape        0.0310
58    59    Arcanine        0.0170
61    62   Poliwrath        0.0110
63    64     Kadabra        0.0270
64    65    Alakazam        0.0073
66    67     Machoke        0.0340
67    68     Machamp        0.0068
70    71  Victreebel        0.0059
75    76       Golem        0.0047
77    78    Rapidash        0.0110
79    80     Slowbro        0.0360
81    82    Magneton        0.0230
82    83  Farfetch'd        0.0212
86    87     Dewgong        0.0130
88    89         Muk        0.0031
90    91    Cloyster        0.0150
93    94      Gengar        0.0067
100  101   Electrode        0.0200
102  103   Exeggutor        0.0140
104  105     Marowak        0.0200
105  106   Hitmonlee        0.0200
106  107  Hitmonchan        0.0220
107  108   Lickitung        0.0110
109  110     Weezing        0.0160
111  112      Rhydon        0.0220
112  113     Chansey        0.0130
114  115  Kangaskhan        0.0086
116  117      Seadra        0.0340
120  121     Starmie        0.0340
121  122    Mr. Mime        0.0031
129  130    Gyarados        0.0032
130  131      Lapras        0.0060
131  132       Ditto        0.0000
133  134    Vaporeon        0.0140
134  135     Jolteon        0.0120
135  136     Flareon        0.0170
136  137     Porygon        0.0120
138  139     Omastar        0.0061
140  141    Kabutops        0.0032
141  142  Aerodactyl        0.0180
142  143     Snorlax        0.0160
143  144    Articuno        0.0000
144  145      Zapdos        0.0000
145  146     Moltres        0.0000
147  148   Dragonair        0.0200
148  149   Dragonite        0.0011
149  150      Mewtwo        0.0000
150  151         Mew        0.0000

**Q2:Get all Pokemons that have less than 4 weaknesses**

In [5]:
df.shape

(151, 17)

In [6]:
df['weaknesses'][0]

"['Fire', 'Ice', 'Flying', 'Psychic']"

In [7]:
type(df['weaknesses'][0])

str

#### since the list of weaknesses is given as a string we need to convert it into a list to count the weaknesses

In [8]:
import warnings
warnings.filterwarnings('ignore')

In [9]:

for i in range(151):
    df['weaknesses'][i] = df['weaknesses'][i].replace('[','').replace(']','').split(',')

In [10]:
len(df['weaknesses'][0])

4

In [11]:
# create a new column of count of weaknesses
df['no:of weakneses'] = df['weaknesses'].apply(lambda x:len(x))

## pokemans having less than 4 weaknesses

In [12]:
df[df['no:of weakneses'] < 4][['name','weaknesses','no:of weakneses']]

                   name                           weaknesses  no:of weakneses
3            Charmander        ['Water',  'Ground',  'Rock']                3
4            Charmeleon        ['Water',  'Ground',  'Rock']                3
5             Charizard      ['Water',  'Electric',  'Rock']                3
6              Squirtle               ['Electric',  'Grass']                2
7             Wartortle               ['Electric',  'Grass']                2
8             Blastoise               ['Electric',  'Grass']                2
9              Caterpie         ['Fire',  'Flying',  'Rock']                3
10              Metapod         ['Fire',  'Flying',  'Rock']                3
15               Pidgey                ['Electric',  'Rock']                2
16            Pidgeotto                ['Electric',  'Rock']                2
17              Pidgeot                ['Electric',  'Rock']                2
18              Rattata                         ['Fighting']                1
19             Raticate                         ['Fighting']                1
20              Spearow                ['Electric',  'Rock']                2
21               Fearow                ['Electric',  'Rock']                2
22                Ekans               ['Ground',  'Psychic']                2
23                Arbok               ['Ground',  'Psychic']                2
24              Pikachu                           ['Ground']                1
25               Raichu                           ['Ground']                1
26            Sandshrew          ['Water',  'Grass',  'Ice']                3
27            Sandslash          ['Water',  'Grass',  'Ice']                3
28   Nidoran ♀ (Female)               ['Ground',  'Psychic']                2
29             Nidorina               ['Ground',  'Psychic']                2
31     Nidoran ♂ (Male)               ['Ground',  'Psychic']                2
32             Nidorino               ['Ground',  'Psychic']                2
34             Clefairy                         ['Fighting']                1
35             Clefable                         ['Fighting']                1
36               Vulpix        ['Water',  'Ground',  'Rock']                3
37            Ninetales        ['Water',  'Ground',  'Rock']                3
38           Jigglypuff                         ['Fighting']                1
39           Wigglytuff                         ['Fighting']                1
49              Diglett          ['Water',  'Grass',  'Ice']                3
50              Dugtrio          ['Water',  'Grass',  'Ice']                3
51               Meowth                         ['Fighting']                1
52              Persian                         ['Fighting']                1
53              Psyduck               ['Electric',  'Grass']                2
54              Golduck               ['Electric',  'Grass']                2
55               Mankey     ['Flying',  'Psychic',  'Fairy']                3
56             Primeape     ['Flying',  'Psychic',  'Fairy']                3
57            Growlithe        ['Water',  'Ground',  'Rock']                3
58             Arcanine        ['Water',  'Ground',  'Rock']                3
59              Poliwag               ['Electric',  'Grass']                2
60            Poliwhirl               ['Electric',  'Grass']                2
62                 Abra           ['Bug',  'Ghost',  'Dark']                3
63              Kadabra           ['Bug',  'Ghost',  'Dark']                3
64             Alakazam           ['Bug',  'Ghost',  'Dark']                3
65               Machop     ['Flying',  'Psychic',  'Fairy']                3
66              Machoke     ['Flying',  'Psychic',  'Fairy']                3
67              Machamp     ['Flying',  'Psychic',  'Fairy']                3
71            Tentacool  ['Electric',  'Ground',  'Psychic']                3
72           Tentacruel  ['Electric',  'Ground',  'Psychic']                3
76               Ponyta        ['Water',  'Ground',  'Rock']                3
77             Rapidash        ['Water',  'Ground',  'Rock']                3
80            Magnemite        ['Fire',  'Water',  'Ground']                3
81             Magneton        ['Fire',  'Water',  'Ground']                3
82           Farfetch'd                ['Electric',  'Rock']                2
83                Doduo                ['Electric',  'Rock']                2
84               Dodrio                ['Electric',  'Rock']                2
85                 Seel               ['Electric',  'Grass']                2
87               Grimer               ['Ground',  'Psychic']                2
88                  Muk               ['Ground',  'Psychic']                2
89             Shellder               ['Electric',  'Grass']                2
95              Drowzee           ['Bug',  'Ghost',  'Dark']                3
96                Hypno           ['Bug',  'Ghost',  'Dark']                3
97               Krabby               ['Electric',  'Grass']                2
98              Kingler               ['Electric',  'Grass']                2
99              Voltorb                           ['Ground']                1
100           Electrode                           ['Ground']                1
103              Cubone          ['Water',  'Grass',  'Ice']                3
104             Marowak          ['Water',  'Grass',  'Ice']                3
105           Hitmonlee     ['Flying',  'Psychic',  'Fairy']                3
106          Hitmonchan     ['Flying',  'Psychic',  'Fairy']                3
107           Lickitung                         ['Fighting']                1
108             Koffing               ['Ground',  'Psychic']                2
109             Weezing               ['Ground',  'Psychic']                2
112             Chansey                         ['Fighting']                1
114          Kangaskhan                         ['Fighting']                1
115              Horsea               ['Electric',  'Grass']                2
116              Seadra               ['Electric',  'Grass']                2
117             Goldeen               ['Electric',  'Grass']                2
118             Seaking               ['Electric',  'Grass']                2
119              Staryu               ['Electric',  'Grass']                2
121            Mr. Mime           ['Bug',  'Ghost',  'Dark']                3
124          Electabuzz                           ['Ground']                1
125              Magmar        ['Water',  'Ground',  'Rock']                3
126              Pinsir         ['Fire',  'Flying',  'Rock']                3
127              Tauros                         ['Fighting']                1
128            Magikarp               ['Electric',  'Grass']                2
129            Gyarados                ['Electric',  'Rock']                2
131               Ditto                         ['Fighting']                1
132               Eevee                         ['Fighting']                1
133            Vaporeon               ['Electric',  'Grass']                2
134             Jolteon                           ['Ground']                1
135             Flareon        ['Water',  'Ground',  'Rock']                3
136             Porygon                         ['Fighting']                1
142             Snorlax                         ['Fighting']                1
144              Zapdos                     ['Ice',  'Rock']                2
145             Moltres      ['Water',  'Electric',  'Rock']                3
146             Dratini         ['Ice',  'Dragon',  'Fairy']                3
147           Dragonair         ['Ice',  'Dragon',  'Fairy']                3
149              Mewtwo           ['Bug',  'Ghost',  'Dark']                3
150                 Mew           ['Bug',  'Ghost',  'Dark']                3

**Get all Pokemons that have no multipliers at all**

## pokemans that have no multipliers

In [13]:
df[df['multipliers'].isnull()][['name','multipliers']]

           name multipliers
2      Venusaur         NaN
5     Charizard         NaN
8     Blastoise         NaN
11   Butterfree         NaN
14     Beedrill         NaN
17      Pidgeot         NaN
19     Raticate         NaN
21       Fearow         NaN
23        Arbok         NaN
25       Raichu         NaN
27    Sandslash         NaN
30    Nidoqueen         NaN
33     Nidoking         NaN
35     Clefable         NaN
37    Ninetales         NaN
39   Wigglytuff         NaN
41       Golbat         NaN
44    Vileplume         NaN
46     Parasect         NaN
48     Venomoth         NaN
50      Dugtrio         NaN
52      Persian         NaN
54      Golduck         NaN
56     Primeape         NaN
58     Arcanine         NaN
61    Poliwrath         NaN
64     Alakazam         NaN
67      Machamp         NaN
70   Victreebel         NaN
72   Tentacruel         NaN
75        Golem         NaN
77     Rapidash         NaN
79      Slowbro         NaN
81     Magneton         NaN
82   Farfetch'd         NaN
84       Dodrio         NaN
86      Dewgong         NaN
88          Muk         NaN
90     Cloyster         NaN
93       Gengar         NaN
94         Onix         NaN
96        Hypno         NaN
98      Kingler         NaN
100   Electrode         NaN
102   Exeggutor         NaN
104     Marowak         NaN
105   Hitmonlee         NaN
106  Hitmonchan         NaN
107   Lickitung         NaN
109     Weezing         NaN
111      Rhydon         NaN
112     Chansey         NaN
113     Tangela         NaN
114  Kangaskhan         NaN
116      Seadra         NaN
118     Seaking         NaN
120     Starmie         NaN
121    Mr. Mime         NaN
122     Scyther         NaN
123        Jynx         NaN
124  Electabuzz         NaN
125      Magmar         NaN
126      Pinsir         NaN
127      Tauros         NaN
129    Gyarados         NaN
130      Lapras         NaN
131       Ditto         NaN
133    Vaporeon         NaN
134     Jolteon         NaN
135     Flareon         NaN
136     Porygon         NaN
138     Omastar         NaN
140    Kabutops         NaN
141  Aerodactyl         NaN
142     Snorlax         NaN
143    Articuno         NaN
144      Zapdos         NaN
145     Moltres         NaN
148   Dragonite         NaN
149      Mewtwo         NaN
150         Mew         NaN

**Get all Pokemons that do not have more than 2 evolutions**

#### number of evolutions of pokeman will be  previous evolutions+next_evolutions

In [14]:
df['next_evolution'][0]

"[{'num': '002', 'name': 'Ivysaur'}, {'num': '003', 'name': 'Venusaur'}]"

In [15]:
type(df['next_evolution'][0])

str

In [16]:
df.next_evolution.info()

<class 'pandas.core.series.Series'>
RangeIndex: 151 entries, 0 to 150
Series name: next_evolution
Non-Null Count  Dtype
--------------  -----
70 non-null     object
dtypes: object(1)
memory usage: 1.3+ KB

In [17]:
type(df['prev_evolution'][0])

float

#### since data type of next evolution and previous evolution are of string as well as float( dtype of nan is float), we need to convert dtype to string so that we can split it to make a list, then  the length of list returns number of evolutions

In [18]:
df['next_evolution'] = df['next_evolution'].astype('str')
df['prev_evolution'] = df['prev_evolution'].astype('str')

In [19]:
for i in range(151):
    df['next_evolution'][i] = df['next_evolution'][i].split('},')
    
for i in range(151):
    df['prev_evolution'][i] = df['prev_evolution'][i].split('},')

In [20]:
df['next_evl_count'] = df['next_evolution'].apply(lambda x:0 if x==['nan'] else len(x))
df['prev_evl_count'] = df['prev_evolution'].apply(lambda x:0 if x==['nan'] else len(x))

In [21]:
current_life = 1
df['total_evolutions'] = df['prev_evl_count'] + current_life + df['next_evl_count']

### Pokemons that do not have more than 2 evolutions

In [22]:
df[df['total_evolutions'] <= 2][['name','prev_evolution','next_evolution','total_evolutions']]

,name,prev_evolution,next_evolution,total_evolutions
18,Rattata,[nan],"[[{'num': '020', 'name': 'Raticate'}]]",2
19,Raticate,"[[{'num': '019', 'name': 'Rattata'}]]",[nan],2
20,Spearow,[nan],"[[{'num': '022', 'name': 'Fearow'}]]",2
21,Fearow,"[[{'num': '021', 'name': 'Spearow'}]]",[nan],2
22,Ekans,[nan],"[[{'num': '024', 'name': 'Arbok'}]]",2
23,Arbok,"[[{'num': '023', 'name': 'Ekans'}]]",[nan],2
24,Pikachu,[nan],"[[{'num': '026', 'name': 'Raichu'}]]",2
25,Raichu,"[[{'num': '025', 'name': 'Pikachu'}]]",[nan],2
26,Sandshrew,[nan],"[[{'num': '028', 'name': 'Sandslash'}]]",2
27,Sandslash,"[[{'num': '027', 'name': 'Sandshrew'}]]",[nan],2
34,Clefairy,[nan],"[[{'num': '036', 'name': 'Clefable'}]]",2
35,Clefable,"[[{'num': '035', 'name': 'Clefairy'}]]",[nan],2
36,Vulpix,[nan],"[[{'num': '038', 'name': 'Ninetales'}]]",2
37,Ninetales,"[[{'num': '037', 'name': 'Vulpix'}]]",[nan],2
38,Jigglypuff,[nan],"[[{'num': '040', 'name': 'Wigglytuff'}]]",2
39,Wigglytuff,"[[{'num': '039', 'name': 'Jigglypuff'}]]",[nan],2
40,Zubat,[nan],"[[{'num': '042', 'name': 'Golbat'}]]",2
41,Golbat,"[[{'num': '041', 'name': 'Zubat'}]]",[nan],2
45,Paras,[nan],"[[{'num': '047', 'name': 'Parasect'}]]",2
46,Parasect,"[[{'num': '046', 'name': 'Paras'}]]",[nan],2
47,Venonat,[nan],"[[{'num': '049', 'name': 'Venomoth'}]]",2
48,Venomoth,"[[{'num': '048', 'name': 'Venonat'}]]",[nan],2
49,Diglett,[nan],"[[{'num': '051', 'name': 'Dugtrio'}]]",2
50,Dugtrio,"[[{'num': '050', 'name': 'Diglett'}]]",[nan],2
51,Meowth,[nan],"[[{'num': '053', 'name': 'Persian'}]]",2
52,Persian,"[[{'num': '052', 'name': 'Meowth'}]]",[nan],2
53,Psyduck,[nan],"[[{'num': '055', 'name': 'Golduck'}]]",2
54,Golduck,"[[{'num': '054', 'name': 'Psyduck'}]]",[nan],2
55,Mankey,[nan],"[[{'num': '057', 'name': 'Primeape'}]]",2
56,Primeape,"[[{'num': '056', 'name': 'Mankey'}]]",[nan],2
57,Growlithe,[nan],"[[{'num': '059', 'name': 'Arcanine'}]]",2
58,Arcanine,"[[{'num': '058', 'name': 'Growlithe'}]]",[nan],2
71,Tentacool,[nan],"[[{'num': '073', 'name': 'Tentacruel'}]]",2
72,Tentacruel,"[[{'num': '072', 'name': 'Tentacool'}]]",[nan],2
76,Ponyta,[nan],"[[{'num': '078', 'name': 'Rapidash'}]]",2
77,Rapidash,"[[{'num': '077', 'name': 'Ponyta'}]]",[nan],2
78,Slowpoke,[nan],"[[{'num': '080', 'name': 'Slowbro'}]]",2
79,Slowbro,"[[{'num': '079', 'name': 'Slowpoke'}]]",[nan],2
80,Magnemite,[nan],"[[{'num': '082', 'name': 'Magneton'}]]",2
81,Magneton,"[[{'num': '081', 'name': 'Magnemite'}]]",[nan],2
82,Farfetch'd,[nan],[nan],1
83,Doduo,[nan],"[[{'num': '085', 'name': 'Dodrio'}]]",2
84,Dodrio,"[[{'num': '084', 'name': 'Doduo'}]]",[nan],2
85,Seel,[nan],"[[{'num': '087', 'name': 'Dewgong'}]]",2
86,Dewgong,"[[{'num': '086', 'name': 'Seel'}]]",[nan],2
87,Grimer,[nan],"[[{'num': '089', 'name': 'Muk'}]]",2
88,Muk,"[[{'num': '088', 'name': 'Grimer'}]]",[nan],2
89,Shellder,[nan],"[[{'num': '091', 'name': 'Cloyster'}]]",2
90,Cloyster,"[[{'num': '090', 'name': 'Shellder'}]]",[nan],2
94,Onix,[nan],[nan],1
95,Drowzee,[nan],"[[{'num': '097', 'name': 'Hypno'}]]",2
96,Hypno,"[[{'num': '096', 'name': 'Drowzee'}]]",[nan],2
97,Krabby,[nan],"[[{'num': '099', 'name': 'Kingler'}]]",2
98,Kingler,"[[{'num': '098', 'name': 'Krabby'}]]",[nan],2
99,Voltorb,[nan],"[[{'num': '101', 'name': 'Electrode'}]]",2
100,Electrode,"[[{'num': '100', 'name': 'Voltorb'}]]",[nan],2
101,Exeggcute,[nan],"[[{'num': '103', 'name': 'Exeggutor'}]]",2
102,Exeggutor,"[[{'num': '102', 'name': 'Exeggcute'}]]",[nan],2
103,Cubone,[nan],"[[{'num': '105', 'name': 'Marowak'}]]",2
104,Marowak,"[[{'num': '104', 'name': 'Cubone'}]]",[nan],2
105,Hitmonlee,[nan],[nan],1
106,Hitmonchan,[nan],[nan],1
107,Lickitung,[nan],[nan],1
108,Koffing,[nan],"[[{'num': '110', 'name': 'Weezing'}]]",2
109,Weezing,"[[{'num': '109', 'name': 'Koffing'}]]",[nan],2
110,Rhyhorn,[nan],"[[{'num': '112', 'name': 'Rhydon'}]]",2
111,Rhydon,"[[{'num': '111', 'name': 'Rhyhorn'}]]",[nan],2
112,Chansey,[nan],[nan],1
113,Tangela,[nan],[nan],1
114,Kangaskhan,[nan],[nan],1
115,Horsea,[nan],"[[{'num': '117', 'name': 'Seadra'}]]",2
116,Seadra,"[[{'num': '116', 'name': 'Horsea'}]]",[nan],2
117,Goldeen,[nan],"[[{'num': '119', 'name': 'Seaking'}]]",2
118,Seaking,"[[{'num': '118', 'name': 'Goldeen'}]]",[nan],2
119,Staryu,[nan],"[[{'num': '121', 'name': 'Starmie'}]]",2
120,Starmie,"[[{'num': '120', 'name': 'Staryu'}]]",[nan],2
121,Mr. Mime,[nan],[nan],1
122,Scyther,[nan],[nan],1
123,Jynx,[nan],[nan],1
124,Electabuzz,[nan],[nan],1
125,Magmar,[nan],[nan],1
126,Pinsir,[nan],[nan],1
127,Tauros,[nan],[nan],1
128,Magikarp,[nan],"[[{'num': '130', 'name': 'Gyarados'}]]",2
129,Gyarados,"[[{'num': '129', 'name': 'Magikarp'}]]",[nan],2
130,Lapras,[nan],[nan],1
131,Ditto,[nan],[nan],1
133,Vaporeon,"[[{'num': '133', 'name': 'Eevee'}]]",[nan],2
134,Jolteon,"[[{'num': '133', 'name': 'Eevee'}]]",[nan],2
135,Flareon,"[[{'num': '133', 'name': 'Eevee'}]]",[nan],2
136,Porygon,[nan],[nan],1
137,Omanyte,[nan],"[[{'num': '139', 'name': 'Omastar'}]]",2
138,Omastar,"[[{'num': '138', 'name': 'Omanyte'}]]",[nan],2
139,Kabuto,[nan],"[[{'num': '141', 'name': 'Kabutops'}]]",2
140,Kabutops,"[[{'num': '140', 'name': 'Kabuto'}]]",[nan],2
141,Aerodactyl,[nan],[nan],1
142,Snorlax,[nan],[nan],1
143,Articuno,[nan],[nan],1
144,Zapdos,[nan],[nan],1
145,Moltres,[nan],[nan],1
149,Mewtwo,[nan],[nan],1
150,Mew,[nan],[nan],1

**Get all Pokemons whose spawn time is less than 300 seconds**

In [23]:
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,no:of weakneses,next_evl_count,prev_evl_count,total_evolutions
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,69.0,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[[{'num': '002', 'name': 'Ivysaur', {'num': '...",[nan],4,2,0,3
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,4.2,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[[{'num': '003', 'name': 'Venusaur'}]]","[[{'num': '001', 'name': 'Bulbasaur'}]]",4,1,1,3
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,1.7,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",[nan],"[[{'num': '001', 'name': 'Bulbasaur', {'num':...",4,0,2,3
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,25.3,08:45,[1.65],"['Water', 'Ground', 'Rock']","[[{'num': '005', 'name': 'Charmeleon', {'num'...",[nan],3,2,0,3
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,1.2,19:00,[1.79],"['Water', 'Ground', 'Rock']","[[{'num': '006', 'name': 'Charizard'}]]","[[{'num': '004', 'name': 'Charmander'}]]",3,1,1,3

In [24]:
type(df['spawn_time'][0])

str

In [25]:
df['spawn_time'] = df['spawn_time'].astype('str')

In [26]:
for i in range(151):
    df['spawn_time'][i] = df['spawn_time'][i].split(':')

In [27]:
df['spawn_min'] = df['spawn_time'].apply(lambda x:0 if x==['nan'] else x[0]).astype('int')
df['spawn_sec'] = df['spawn_time'].apply(lambda x:0 if x==['nan'] else x[1]).astype('int')

In [28]:
df['spawn_time_seconds'] = (df['spawn_min']*60) + df['spawn_sec']

### Pokemons whose spawn time is less than 300 seconds

In [29]:
df[df['spawn_time_seconds']<300][['name','spawn_time','spawn_time_seconds']]

                   name spawn_time  spawn_time_seconds
6              Squirtle   [04, 25]                 265
8             Blastoise   [00, 06]                   6
10              Metapod   [02, 11]                 131
12               Weedle   [02, 21]                 141
13               Kakuna   [02, 30]                 150
14             Beedrill   [04, 50]                 290
15               Pidgey   [01, 34]                  94
16            Pidgeotto   [01, 30]                  90
17              Pidgeot   [01, 50]                 110
18              Rattata   [01, 55]                 115
19             Raticate   [01, 56]                 116
21               Fearow   [01, 11]                  71
23                Arbok   [01, 50]                 110
24              Pikachu   [04, 00]                 240
26            Sandshrew   [01, 58]                 118
28   Nidoran ♀ (Female)   [01, 51]                 111
31     Nidoran ♂ (Male)   [01, 12]                  72
34             Clefairy   [03, 30]                 210
35             Clefable   [03, 29]                 209
37            Ninetales   [01, 32]                  92
41               Golbat   [02, 15]                 135
42               Oddish   [03, 58]                 238
45                Paras   [01, 42]                 102
46             Parasect   [01, 22]                  82
47              Venonat   [02, 31]                 151
49              Diglett   [02, 22]                 142
51               Meowth   [02, 54]                 174
52              Persian   [02, 44]                 164
53              Psyduck   [03, 41]                 221
57            Growlithe   [03, 57]                 237
58             Arcanine   [03, 11]                 191
59              Poliwag   [03, 40]                 220
61            Poliwrath   [01, 32]                  92
62                 Abra   [04, 30]                 270
65               Machop   [01, 55]                 115
67              Machamp   [02, 55]                 175
68           Bellsprout   [04, 10]                 250
71            Tentacool   [03, 20]                 200
74             Graveler   [04, 53]                 293
76               Ponyta   [02, 50]                 170
77             Rapidash   [04, 00]                 240
79              Slowbro   [02, 56]                 176
80            Magnemite   [04, 04]                 244
82           Farfetch'd   [01, 09]                  69
84               Dodrio   [02, 12]                 132
88                  Muk   [01, 28]                  88
90             Cloyster   [02, 33]                 153
91               Gastly   [04, 21]                 261
92              Haunter   [00, 10]                  10
93               Gengar   [03, 55]                 235
94                 Onix   [01, 18]                  78
95              Drowzee   [01, 51]                 111
96                Hypno   [02, 17]                 137
97               Krabby   [03, 33]                 213
98              Kingler   [03, 44]                 224
99              Voltorb   [04, 36]                 276
100           Electrode   [04, 10]                 250
103              Cubone   [01, 51]                 111
104             Marowak   [03, 59]                 239
105           Hitmonlee   [03, 59]                 239
107           Lickitung   [02, 46]                 166
110             Rhyhorn   [03, 21]                 201
112             Chansey   [04, 46]                 286
114          Kangaskhan   [02, 40]                 160
115              Horsea   [02, 53]                 173
116              Seadra   [03, 18]                 198
117             Goldeen   [03, 14]                 194
121            Mr. Mime   [01, 51]                 111
124          Electabuzz   [04, 28]                 268
126              Pinsir   [03, 25]                 205
127              Tauros   [00, 37]                  37
129            Gyarados   [02, 15]                 135
131               Ditto      [nan]                   0
134             Jolteon   [02, 30]                 150
136             Porygon   [02, 49]                 169
139              Kabuto   [00, 05]                   5
143            Articuno      [nan]                   0
144              Zapdos      [nan]                   0
145             Moltres      [nan]                   0
149              Mewtwo      [nan]                   0
150                 Mew      [nan]                   0

**Get all Pokemon who have more than two types of capabilities**

In [30]:
# craeting a new column with some random value,in the next step we will update it with correct value

df['no_of_types'] = 151

In [31]:
for i in range(151):
    df['no_of_types'][i] = len(df['type'][i].split(', '))

In [32]:
df[df['no_of_types']>2][['name','type']]

Empty DataFrame
Columns: [name, type]
Index: []

In [33]:
df[df['no_of_types']<=2][['name','type']]

                   name                    type
0             Bulbasaur     ['Grass', 'Poison']
1               Ivysaur     ['Grass', 'Poison']
2              Venusaur     ['Grass', 'Poison']
3            Charmander                ['Fire']
4            Charmeleon                ['Fire']
5             Charizard      ['Fire', 'Flying']
6              Squirtle               ['Water']
7             Wartortle               ['Water']
8             Blastoise               ['Water']
9              Caterpie                 ['Bug']
10              Metapod                 ['Bug']
11           Butterfree       ['Bug', 'Flying']
12               Weedle       ['Bug', 'Poison']
13               Kakuna       ['Bug', 'Poison']
14             Beedrill       ['Bug', 'Poison']
15               Pidgey    ['Normal', 'Flying']
16            Pidgeotto    ['Normal', 'Flying']
17              Pidgeot    ['Normal', 'Flying']
18              Rattata              ['Normal']
19             Raticate              ['Normal']
20              Spearow    ['Normal', 'Flying']
21               Fearow    ['Normal', 'Flying']
22                Ekans              ['Poison']
23                Arbok              ['Poison']
24              Pikachu            ['Electric']
25               Raichu            ['Electric']
26            Sandshrew              ['Ground']
27            Sandslash              ['Ground']
28   Nidoran ♀ (Female)              ['Poison']
29             Nidorina              ['Poison']
30            Nidoqueen    ['Poison', 'Ground']
31     Nidoran ♂ (Male)              ['Poison']
32             Nidorino              ['Poison']
33             Nidoking    ['Poison', 'Ground']
34             Clefairy              ['Normal']
35             Clefable              ['Normal']
36               Vulpix                ['Fire']
37            Ninetales                ['Fire']
38           Jigglypuff              ['Normal']
39           Wigglytuff              ['Normal']
40                Zubat    ['Poison', 'Flying']
41               Golbat    ['Poison', 'Flying']
42               Oddish     ['Grass', 'Poison']
43                Gloom     ['Grass', 'Poison']
44            Vileplume     ['Grass', 'Poison']
45                Paras        ['Bug', 'Grass']
46             Parasect        ['Bug', 'Grass']
47              Venonat       ['Bug', 'Poison']
48             Venomoth       ['Bug', 'Poison']
49              Diglett              ['Ground']
50              Dugtrio              ['Ground']
51               Meowth              ['Normal']
52              Persian              ['Normal']
53              Psyduck               ['Water']
54              Golduck               ['Water']
55               Mankey            ['Fighting']
56             Primeape            ['Fighting']
57            Growlithe                ['Fire']
58             Arcanine                ['Fire']
59              Poliwag               ['Water']
60            Poliwhirl               ['Water']
61            Poliwrath   ['Water', 'Fighting']
62                 Abra             ['Psychic']
63              Kadabra             ['Psychic']
64             Alakazam             ['Psychic']
65               Machop            ['Fighting']
66              Machoke            ['Fighting']
67              Machamp            ['Fighting']
68           Bellsprout     ['Grass', 'Poison']
69           Weepinbell     ['Grass', 'Poison']
70           Victreebel     ['Grass', 'Poison']
71            Tentacool     ['Water', 'Poison']
72           Tentacruel     ['Water', 'Poison']
73              Geodude      ['Rock', 'Ground']
74             Graveler      ['Rock', 'Ground']
75                Golem      ['Rock', 'Ground']
76               Ponyta                ['Fire']
77             Rapidash                ['Fire']
78             Slowpoke    ['Water', 'Psychic']
79              Slowbro    ['Water', 'Psychic']
80            Magnemite            ['Electric']
81             Magneton            ['Electric']
82           Farfetch'd    ['Normal', 'Flying']
83                Doduo    ['Normal', 'Flying']
84               Dodrio    ['Normal', 'Flying']
85                 Seel               ['Water']
86              Dewgong        ['Water', 'Ice']
87               Grimer              ['Poison']
88                  Muk              ['Poison']
89             Shellder               ['Water']
90             Cloyster        ['Water', 'Ice']
91               Gastly     ['Ghost', 'Poison']
92              Haunter     ['Ghost', 'Poison']
93               Gengar     ['Ghost', 'Poison']
94                 Onix      ['Rock', 'Ground']
95              Drowzee             ['Psychic']
96                Hypno             ['Psychic']
97               Krabby               ['Water']
98              Kingler               ['Water']
99              Voltorb            ['Electric']
100           Electrode            ['Electric']
101           Exeggcute    ['Grass', 'Psychic']
102           Exeggutor    ['Grass', 'Psychic']
103              Cubone              ['Ground']
104             Marowak              ['Ground']
105           Hitmonlee            ['Fighting']
106          Hitmonchan            ['Fighting']
107           Lickitung              ['Normal']
108             Koffing              ['Poison']
109             Weezing              ['Poison']
110             Rhyhorn      ['Ground', 'Rock']
111              Rhydon      ['Ground', 'Rock']
112             Chansey              ['Normal']
113             Tangela               ['Grass']
114          Kangaskhan              ['Normal']
115              Horsea               ['Water']
116              Seadra               ['Water']
117             Goldeen               ['Water']
118             Seaking               ['Water']
119              Staryu               ['Water']
120             Starmie    ['Water', 'Psychic']
121            Mr. Mime             ['Psychic']
122             Scyther       ['Bug', 'Flying']
123                Jynx      ['Ice', 'Psychic']
124          Electabuzz            ['Electric']
125              Magmar                ['Fire']
126              Pinsir                 ['Bug']
127              Tauros              ['Normal']
128            Magikarp               ['Water']
129            Gyarados     ['Water', 'Flying']
130              Lapras        ['Water', 'Ice']
131               Ditto              ['Normal']
132               Eevee              ['Normal']
133            Vaporeon               ['Water']
134             Jolteon            ['Electric']
135             Flareon                ['Fire']
136             Porygon              ['Normal']
137             Omanyte       ['Rock', 'Water']
138             Omastar       ['Rock', 'Water']
139              Kabuto       ['Rock', 'Water']
140            Kabutops       ['Rock', 'Water']
141          Aerodactyl      ['Rock', 'Flying']
142             Snorlax              ['Normal']
143            Articuno       ['Ice', 'Flying']
144              Zapdos  ['Electric', 'Flying']
145             Moltres      ['Fire', 'Flying']
146             Dratini              ['Dragon']
147           Dragonair              ['Dragon']
148           Dragonite    ['Dragon', 'Flying']
149              Mewtwo             ['Psychic']
150                 Mew             ['Psychic']

## #There are no Pokemon who have more than two types of capabilities